# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1El6qDRcPnQa8r78OCjd27VRgL42BHm6M
"""

# Google Colab uchun kerakli kutubxonalarni o'rnatish
!pip install scikit-learn matplotlib --quiet

# Kutubxonalarni import qilish
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Ma'lumotlar yaratish (sun'iy ma'lumotlar)
np.random.seed(42)
X = np.random.randn(200, 2)  # X koordinatalar
y = (X[:, 0] + X[:, 1] > 0).astype(int)  # Maqsad (1 yoki 0)

# Ma'lumotlarni ko'rish
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis')
plt.title("Dastlabki ma'lumotlar")
plt.show()

# Ma'lumotlarni bo'lish (train-test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Logistik regressiya modelini yaratish
model = LogisticRegression()
model.fit(X_train, y_train)

# Test ma'lumotlariga bashorat qilish
y_pred = model.predict(X_test)

# Natijalarni baholash
accuracy = accuracy_score(y_test, y_pred)
print(f"Modelning aniqligi: {accuracy * 100:.2f}%")

# Bashoratlar grafikasi
plt.scatter(X_test[:, 0], X_test[:, 1], c=y_pred, cmap='coolwarm', alpha=0.7)
plt.title("Model bashoratlari")
plt.show()